// const products = 
// [
//     {
//         id:1,
//         img:"images/baskets/baskets-1.png",
//         name:"Basket",
//         description:"Basket 10 legs",
//         price:133.000,
//     },
//     {
//         id:2,
//         img:"images/baskets/baskets-2.png",
//         name:"Basket",
//         description:"Basket L (26 wings)",
//         price:133.000,
//     },
//     {
//         id:3,
//         img:"images/baskets/baskets-3.png",
//         name:"Basket",
//         description:"Basket M (18 wings)",
//         price:107.000,
//     },
//     {
//         id:4,
//         img:"images/baskets/baskets-3.png",
//         name:"Basket",
//         description:"Basket S (12 wings)",
//         price:76.000,
//     },
//     {
//         id:5,
//         img:"images/baskets/baskets-4.png",
//         name:"Basket",
//         description:"Basket-Duet origin",
//         price:85.000,
//     },
//     {
//         id:6,
//         img:"images/baskets/baskets-4.png",
//         name:"Basket",
//         description:"Basket-Duet spicy",
//         price:85.000,
//     },
//     {
//         id:7,
//         img:"images/baskets/baskets-5.png",
//         name:"Basket",
//         description:"Mix Box",
//         price:26.500,
//     },
//     {
//         id:8,
//         img:"images/baskets/baskets-6.png",
//         name:"Basket",
//         description:"Nuggets Box",
//         price:25.000,
//     },
//     {
//         id:9,
//         img:"images/baskets/baskets-7.png",
//         name:"Basket",
//         description:"Party Basket",
//         price:25.000,
//     },
//     {
//         id:10,
//         img:"images/baskets/baskets-8.png",
//         name:"Basket",
//         description:"Senders Basket",
//         price:43.500,
//     },
//     {
//         id:11,
//         img:"images/baskets/baskets-9.png",
//         name:"Basket",
//         description:"Friends Box Assorted",
//         price:199.000,
//     },
//     {
//         id:12,
//         img:"images/burgers/burger-1.png",
//         name:"Burgers",
//         description:"Double Chefburger",
//         price:39.000,
//     },
//     {
//         id:13,
//         img:"images/burgers/burger-1.png",
//         name:"Basket",
//         description:"Double Chefburger Spicy",
//         price:39.000,
//     },
//     {
//         id:14,
//         img:"images/burgers/burger-2.png",
//         name:"Burgers",
//         description:"Spicy Chefburger",
//         price:26.000,
//     },
//     {
//         id:15,
//         img:"images/burgers/burger-3.png",
//         name:"Burgers",
//         description:"Cheeseburger",
//         price:22.500,
//     },
//     {
//         id:16,
//         img:"images/burgers/burger-4.png",
//         name:"Burgers",
//         description:"Cheeseburger De Luxe",
//         price:26.000,
//     },
//     {
//         id:17,
//         img:"images/burgers/burger-5.png",
//         name:"Burgers",
//         description:"Chef Towel",
//         price:32.000,
//     },
//     {
//         id:18,
//         img:"images/burgers/burger-5.png",
//         name:"Burgers",
//         description:"Chef Towel Sharp",
//         price:32.000,
//     },
//     {
//         id:19,
//         img:"images/burgers/burger-5.png",
//         name:"Burgers",
//         description:"Chefburger",
//         price:26.000,
//     },
//     {
//         id:20,
//         img:"images/twisters/twister-1.png",
//         name:"Twisters",
//         description:"Boxmaster",
//         price:33.500,
//     },
//     {
//         id:21,
//         img:"images/twisters/twister-2.png",
//         name:"Twisters",
//         description:"Longer",
//         price:17.500,
//     },
//     {
//         id:22,
//         img:"images/twisters/twister-3.png",
//         name:"Twisters",
//         description:"Twister Wedgie",
//         price:26.000,
//     },
//     {
//         id:23,
//         img:"images/twisters/twister-4.png",
//         name:"Twisters",
//         description:"Twister Junior",
//         price:17.500,
//     },
//     {
//         id:24,
//         img:"images/twisters/twister-5.png",
//         name:"Twisters",
//         description:"Twister Original",
//         price:26.000,
//     },
//     {
//         id:25,
//         img:"images/grill/grill-1.png",
//         name:"Chicken",
//         description:"Nuggets 6 pcs",
//         price:15.000,
//     },
//     {
//         id:26,
//         img:"images/grill/grill-2.png",
//         name:"Chicken",
//         description:"Nuggets 8 pcs",
//         price:20.000,
//     },
//     {
//         id:27,
//         img:"images/grill/grill-3.png",
//         name:"Chicken",
//         description:"3 Krylv",
//         price:23.000,
//     },
//     {
//         id:28,
//         img:"images/grill/grill-4.png",
//         name:"Chicken",
//         description:"1 leg",
//         price:15.000,
//     },
//     {
//         id:29,
//         img:"images/grill/grill-5.png",
//         name:"Chicken",
//         description:"2 leg",
//         price:25.000,
//     },
//     {
//         id:30,
//         img:"images/grill/grill-6.png",
//         name:"Chicken",
//         description:"3 leg",
//         price:34.000,
//     },
//     {
//         id:31,
//         img:"images/grill/grill-7.png",
//         name:"Chicken",
//         description:"3 strips original",
//         price:24.000,
//     },
//     {
//         id:32,
//         img:"images/grill/grill-7.png",
//         name:"Chicken",
//         description:"3 strips spicy",
//         price:24.000,
//     },
//     {
//         id:33,
//         img:"images/grill/grill-8.png",
//         name:"Chicken",
//         description:"5 strips original",
//         price:43.000,
//     },
//     {
//         id:34,
//         img:"images/grill/grill-9.png",
//         name:"Chicken",
//         description:"5 wings",
//         price:39.000,
//     },
//     {
//         id:35,
//         img:"images/grill/grill-10.png",
//         name:"Chicken",
//         description:"5 strips original",
//         price:43.000,
//     },
//     {
//         id:36,
//         img:"images/grill/grill-11.png",
//         name:"Chicken",
//         description:"8 wings",
//         price:52.000,
//     },
//     {
//         id:37,
//         img:"images/grill/grill-12.png",
//         name:"Chicken",
//         description:"8 strips original",
//         price:56.000,
//     },
//     {
//         id:38,
//         img:"images/grill/grill-12.png",
//         name:"Chicken",
//         description:"8 strips spicy",
//         price:56.000,
//     },
//     {
//         id:39,
//         img:"images/grill/grill-13.png",
//         name:"Chicken",
//         description:"Bytes are small",
//         price:18.000,
//     },
//     {
//         id:40,
//         img:"images/grill/grill-13.png",
//         name:"Chicken",
//         description:"Bytes average",
//         price:26.000,
//     },
//     {
//         id:41,
//         img:"images/grill/grill-14.png",
//         name:"Chicken",
//         description:"Nuggets 18 pcs",
//         price:42.000,
//     },
//     {
//         id:42,
//         img:"images/free/free-1.png",
//         name:"French Fries",
//         description:"Basket Fries",
//         price:26.500,
//     },
//     {
//         id:43,
//         img:"images/free/free-2.png",
//         name:"French Fries",
//         description:"Bun",
//         price:7.000,
//     },
//     {
//         id:44,
//         img:"images/free/free-3.png",
//         name:"French Fries",
//         description:"Rustic potato stand",
//         price:19.000,
//     },
//     {
//         id:45,
//         img:"images/free/free-4.png",
//         name:"French Fries",
//         description:"French fries small",
//         price:14.000,
//     },
//     {
//         id:46,
//         img:"images/free/free-5.png",
//         name:"French Fries",
//         description:"French fries standard",
//         price:20.000,
//     },
//     {
//         id:47,
//         img:"images/free/free-6.png",
//         name:"French Fries",
//         description:"Hashbrown",
//         price:8.000,
//     },
//     {
//         id:48,
//         img:"images/sauces/sauce-1.png",
//         name:"Sauces",
//         description:"Ketchup tomato",
//         price:5.000,
//     },
//     {
//         id:49,
//         img:"images/sauces/sauce-2.png",
//         name:"Sauces",
//         description:"Ketchup Cheese",
//         price:5.000,
//     },
//     {
//         id:50,
//         img:"images/sauces/sauce-3.png",
//         name:"Sauces",
//         description:"Sweet and sour chili",
//         price:5.000,
//     },
//     {
//         id:51,
//         img:"images/sauces/sauce-4.png",
//         name:"Sauces",
//         description:"Sauce Garlic",
//         price:5.000,
//     },
//     {
//         id:52,
//         img:"images/beverages/fanta.jpg",
//         name:"Beverages",
//         description:"Fanta 0.5",
//         price:12.000,
//     },
//     {
//         id:53,
//         img:"images/beverages/bonaqua.png",
//         name:"Beverages",
//         description:"BonAqua non carbonat 0.5",
//         price:7.000,
//     },
//     {
//         id:54,
//         img:"images/beverages/cola.png",
//         name:"Beverages",
//         description:"Coca-cola 0.5",
//         price:12.000,
//     },
//     {
//         id:55,
//         img:"images/beverages/bonaqua.png",
//         name:"Beverages",
//         description:"BonAqua carbonated",
//         price:7.000,
//     },
//     {
//         id:56,
//         img:"images/beverages/sok.png",
//         name:"Beverages",
//         description:"Orange juice 0.2l",
//         price:7.000,
//     },
//     {
//         id:57,
//         img:"images/beverages/sok-2.png",
//         name:"Beverages",
//         description:"Apple juice 0.2l",
//         price:7.000,
//     },
//     {
//         id:58,
//         img:"images/desserts/dessert-1.png",
//         name:"Beverages",
//         description:"Donut Nut",
//         price:17.000,
//     },
//     {
//         id:59,
//         img:"images/desserts/dessert-2.png",
//         name:"Beverages",
//         description:"Pie Cherry",
//         price:15.000,
//     },
// ]

// ======
// STATE
const btnBasket = document.querySelector(".basket");
const btnCart = document.querySelector(".cart");
const btnCancel = document.querySelector(".cancel");
// Logic
btnBasket.addEventListener("click",function () {
    btnCart.classList.toggle("hidden")
});

btnCancel.addEventListener("click", function() {
    btnCart.classList.toggle("hidden")
})